#!/usr/bin/env python3
"""
Regenerates install.py from the individual module files under src/.

install.py is meant to be the one file someone downloads and runs - see its
own docstring. It's built, not hand-written: this script embeds each real
module's current source verbatim (as a plain triple-quoted string, not
compressed or encoded, so install.py stays auditable) into one bootstrap
file. Run this after editing any of the modules listed in MODULES below, or
after adding/removing one, so install.py doesn't go stale.

The modules live under src/ for a clean repo layout, but install.py still
extracts them flat (directly next to itself, not into a subfolder) when
someone runs it - that's a deliberate, separate choice from this repo's own
organization, made so the standalone follow-up commands this toolkit
documents (`python3 usb_map.py ...`, `python3 cpufriend.py ...`, etc.) stay
exactly as simple for an end user as they've always been, regardless of how
this source repo itself is organized.

Every module here already avoids the sequence ''' internally (this script
asserts that below) - if a future edit introduces one, install.py's own
embedding would break, and this script will refuse to generate it rather
than produce a corrupt bundle. Embedded as raw strings (r'''...''') on
purpose - a module's own source can contain backslash-escapes (e.g. \' or
\n inside one of its own string literals); a non-raw triple-quoted string
would have Python re-interpret those escapes while parsing install.py
itself, silently corrupting the embedded copy (caught by this script's own
round-trip check in build(), which diffs each extraction against the
original before declaring success).
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(HERE, 'src')

# Dependency order matters only for readability here - hackintosh_setup.py
# still imports the others by name once extracted, so Python's own import
# system resolves the real order at run time regardless of this list's
# order. If you add/remove/rename an entry here, update the matching
# root-level ignore list in .gitignore too - see its comment for why.
MODULES = [
    'hw_detect.py',
    'net.py',
    'hardware_report.py',
    'macrecovery.py',
    'partition.py',
    'restore_backup.py',
    'write_basesystem.py',
    'macos_acpi.py',
    'opcore_simplify.py',
    'install_efi.py',
    'imessage.py',
    'usb_map.py',
    'cpufriend.py',
    'hackintosh_setup.py',
]

BOOTSTRAP = '''#!/usr/bin/env python3
"""
Hackintosh EFI/installer builder - single-file installer.

This is the whole toolkit ({module_list}) bundled into
one file, so there's just one thing to download and run on Windows, macOS,
or Linux:

    python3 install.py      (macOS/Linux)
    python install.py       (Windows)

No manual sudo/Administrator prefix needed - see _self_elevate() below;
you'll still see the normal sudo password prompt or Windows UAC dialog,
since this script does not (and should not) bypass that.

Each module's real, unmodified source is embedded below as a plain triple-
quoted string - not compressed or encoded - specifically so this file stays
auditable: read any section below directly to see exactly what will run,
the same as reading that module's own file in the original toolkit.

Generated by build_install.py - don't hand-edit the embedded copies below;
edit the real .py files this came from and re-run `python3 build_install.py`
instead, or just edit the extracted copies this script writes next to
itself on first run (same files, now on disk as normal .py files) and use
those directly from then on.

On first run this:
  1. Self-elevates to root/Administrator if not already (see above).
  2. Extracts every embedded module to a real .py file next to this
     script - so the documented standalone follow-up commands
     (`python3 usb_map.py ...`, `python3 cpufriend.py ...`,
     `python3 imessage.py --apply`) keep working exactly as before,
     using the exact same code, not a separate copy.
  3. Runs the same one-click build hackintosh_setup.py always has - see
     that module's own docstring (extracted alongside this one) for
     exactly what it does and the two situations it still stops to ask
     you about.
"""

import ctypes
import os
import subprocess
import sys

_MODULES = {{
{module_dict_body}
}}


def _self_elevate():
    """
    Re-execs this same script elevated if it isn't already - the one thing
    a truly single-file, one-click installer needs to handle itself rather
    than asking the user to remember `sudo`/"Run as Administrator". Does
    NOT suppress the OS's own elevation prompt (sudo password / UAC dialog)
    - that prompt is Windows/sudo's own security boundary, not this
    toolkit's, and bypassing it would be a real security regression, not a
    convenience.
    """
    if os.name == 'nt':
        if ctypes.windll.shell32.IsUserAnAdmin():
            return
        print('Not running as Administrator - relaunching elevated (accept the UAC prompt)...')
        params = subprocess.list2cmdline([os.path.abspath(__file__)] + sys.argv[1:])
        ret = ctypes.windll.shell32.ShellExecuteW(None, 'runas', sys.executable, params, None, 1)
        if int(ret) <= 32:
            raise SystemExit(
                'Could not relaunch elevated (UAC declined, or failed to launch) - '
                're-run this script yourself from an elevated PowerShell/Command Prompt instead.'
            )
        sys.exit(0)
    else:
        if os.geteuid() == 0:
            return
        print('Not running as root - relaunching with sudo (you may be asked for your password)...')
        try:
            os.execvp('sudo', ['sudo', sys.executable, os.path.abspath(__file__)] + sys.argv[1:])
        except FileNotFoundError:
            raise SystemExit(
                'sudo not found on this system - install it, or re-run this script '
                'yourself as root (e.g. via su).'
            )


def _extract_modules():
    """Writes every embedded module out as a real .py file next to this
    script, and returns that directory. Always overwrites - these are
    generated copies (see this file's own docstring), not meant for hand-
    editing in place; edit the original toolkit and regenerate instead, or
    treat the extracted copies as the new source of truth from here on."""
    here = os.path.dirname(os.path.abspath(__file__))
    for filename, source in _MODULES.items():
        with open(os.path.join(here, filename), 'w') as f:
            f.write(source)
    print(f'Extracted {{len(_MODULES)}} module(s) to {{here}}')
    return here


def main():
    _self_elevate()
    toolkit_dir = _extract_modules()
    if toolkit_dir not in sys.path:
        sys.path.insert(0, toolkit_dir)
    import hackintosh_setup
    hackintosh_setup.main()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        sys.exit('\\nAborted.')
'''


def build():
    module_dict_lines = []
    for filename in MODULES:
        path = os.path.join(SRC_DIR, filename)
        with open(path, 'r') as f:
            source = f.read()
        assert "'''" not in source, (
            f"{filename} contains a ''' sequence - would break install.py's embedding. "
            f"Switch that module's own quoting or update this script's delimiter choice."
        )
        module_dict_lines.append(f"    {filename!r}: r'''{source}''',")

    output = BOOTSTRAP.format(
        module_list=', '.join(MODULES),
        module_dict_body='\n'.join(module_dict_lines),
    )

    out_path = os.path.join(HERE, 'install.py')
    with open(out_path, 'w') as f:
        f.write(output)
    print(f'Wrote {out_path} ({len(output)} bytes, {len(MODULES)} modules embedded)')

    _verify_round_trip(out_path)


def _verify_round_trip(install_py_path):
    """Extracts every module install.py just embedded into a throwaway
    temp dir and diffs each one byte-for-byte against the original it came
    from - catches embedding bugs (e.g. escape sequences inside a module's
    own source getting reinterpreted while parsing install.py itself)
    instead of shipping a silently corrupted bundle."""
    import importlib.util
    import tempfile

    spec = importlib.util.spec_from_file_location('_install_verify', install_py_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    with tempfile.TemporaryDirectory() as tmp:
        for filename, embedded_source in mod._MODULES.items():
            original = os.path.join(SRC_DIR, filename)
            with open(original, 'r') as f:
                original_source = f.read()
            if embedded_source != original_source:
                raise SystemExit(
                    f'Round-trip check failed for {filename}: the embedded copy in '
                    f'install.py does not match the original byte-for-byte. Not shipping '
                    f'a corrupted bundle - fix build_install.py\'s embedding and re-run.'
                )
    print(f'Round-trip check passed: all {len(mod._MODULES)} embedded modules match their originals exactly.')


if __name__ == '__main__':
    build()
